on: [push]

jobs:
  compile_cv:
    runs-on: ubuntu-latest
    name: A job to compile tex
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Builder action step
        uses: ./
